app/Http/routes.php
<?php

Route::group(['middleware' => 'web'], function () {

    Route::get('/', ['as' => 'front', 'uses' => 'SiteController@index']);
    Route::get('about', ['as' => 'about', 'uses' => 'SiteController@about']);

    Route::auth();
    Route::get('confirmation', 'Auth\AuthController@confirmation');
    Route::get('confirmation/success', 'Auth\AuthController@confirmationSuccess');
    Route::get('confirm/{hash}', 'Auth\AuthController@confirm');
    Route::get('blocked', 'Auth\AuthController@blocked');
    Route::get('activate', 'Auth\AuthController@activate');

    Route::get('widgets/alert-box/{hash}', [
        'as' => 'widget.donate_alertbox',
        'uses' => 'WidgetController@donateAlertBox'
    ]);

    Route::get('donate/{username}', [
        'as' => 'donate',
        'uses' => 'DonationController@donate'
    ]);

    Route::post('donate/{username}', 'DonationController@postDonate');

    Route::group(['prefix' => 'dashboard', 'middleware' => 'auth', 'namespace' => 'Dashboard'], function() {

        Route::get('/', [
            'as' => 'dashboard',
            'uses' => 'DashboardController@index'
        ]);

        Route::get('donations', [
            'as' => 'donations',
            'uses' => 'DonationController@index',
        ]);

        Route::get('test-donation', [
            'as' => 'donation.test',
            'uses' => 'DonationController@test'
        ]);

        Route::group(['prefix' => 'widgets', 'as' => 'widget.'], function() {

            Route::get('donation', [
                'as' => 'donation',
                'uses' => 'WidgetController@donateSettings'
            ]);

            Route::post('donation', 'WidgetController@saveDonateSettings');
        });

        /*
         * Настройки
         */
        Route::group(['prefix' => 'settings'], function() {

            Route::get('/', [
                'as' => 'dashboard.settings',
                'uses' => 'SettingsController@getAccount',
            ]);

            Route::post('/', 'SettingsController@postAccount');

            Route::get('donate', [
                'as' => 'dashboard.settings.donate',
                'uses' => 'SettingsController@getDonate'
            ]);

            Route::post('donate', 'SettingsController@postDonate');

            Route::get('withdrawal', [
                'as' => 'dashboard.settings.withdrawal',
                'uses' => 'SettingsController@getWithdrawal'
            ]);

            Route::post('withdrawal', 'SettingsController@postWithdrawal');
        });
    });

    Route::group(['prefix' => 'payment'], function() {
        /**
         * По этому адресу unitpay будет уведомлять о любом изменении в статусе платежа.
         */
        Route::get('proccess', 'PaymentController@proccess');
    });
});

resources/views/partials/header.blade.php
<header class="main-header">

    <!-- Logo -->
    <a href="{{ route('dashboard') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>O</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Alerts</b>Online</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-left navbar-donate-link">

            <div class="input-group">
                <input type="text" class="form-control" value="{{ route('donate', Auth::user()->name) }}" readonly onclick="jQuery(this).select();" title="Ваша ссылка для доната" data-toggle="tooltip" data-placement="bottom"/>
                <div class="input-group-btn">
                    <a href="{{ route('donate', Auth::user()->name) }}" class="btn btn-flat btn-default" title="Открыть в новом окне" target="_blank" data-toggle="tooltip" data-placement="bottom">
                        <i class="fa fa-external-link"></i>
                    </a>
                </div>
            </div>
        </div>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {{--<!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <li><!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <!-- User Image -->
                                            <img src="{{ asset(Auth::user()->settings->get('account_avatar')) }}" class="img-circle" alt="User Image">
                                        </div>
                                        <!-- Message title and timestamp -->
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <!-- The message -->
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li><!-- end message -->
                            </ul><!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li><!-- /.messages-menu -->

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li><!-- end notification -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- Tasks Menu -->
                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li><!-- Task item -->
                                    <a href="#">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <!-- The progress bar -->
                                        <div class="progress xs">
                                            <!-- Change the css width attribute to simulate progress -->
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li><!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>--}}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset(Auth::user()->settings->get('account_avatar')) }}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset(Auth::user()->settings->get('account_avatar')) }}" class="img-circle" alt="User Image">
                            <p>{{ Auth::user()->name }}</p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('dashboard.settings') }}" class="btn btn-default btn-flat">Настройки</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url('logout') }}" class="btn btn-default btn-flat">Выход</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
{{--                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>--}}
            </ul>
        </div>
    </nav>
</header>

resources/views/partials/sidebar.blade.php
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset(Auth::user()->settings->get('account_avatar')) }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">Мой аккаунт</li>
            <!-- Optionally, you can add icons to the links -->
            <li {!! request()->url() == route('dashboard') ? 'class="active"' : '' !!}><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> <span>Панель управления</span></a></li>
            <li {!! request()->url() == route('donations') ? 'class="active"' : '' !!}><a href="{{ route('donations') }}"><i class="fa fa-gift"></i> <span>Мои донаты</span></a></li>

            <li class="treeview {!! in_array(request()->url(), [route('dashboard.settings'), route('dashboard.settings.donate'), route('dashboard.settings.withdrawal')]) ? ' active' : '' !!}">
                <a href="#">
                    <i class="fa fa-cog"></i> <span>Настройки</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>

                <ul class="treeview-menu">
                    <li class="{!! request()->url() == route('dashboard.settings') ? ' active' : '' !!}">
                        <a href="{{ route('dashboard.settings') }}"><i class="fa fa-user"></i> Аккаунт</a>
                    </li>

                    <li class="{!! request()->url() == route('dashboard.settings.donate') ? ' active' : '' !!}">
                        <a href="{{ route('dashboard.settings.donate') }}"><i class="fa fa-credit-card"></i> Донат</a>
                    </li>

                    <li class="{!! request()->url() == route('dashboard.settings.withdrawal') ? ' active' : '' !!}">
                        <a href="{{ route('dashboard.settings.withdrawal') }}"><i class="fa fa-money"></i> Вывод средств</a>
                    </li>
                </ul>
            </li>

            <li class="header">Виджеты</li>
            <li {!! request()->url() == route('widget.donation') ? 'class="active"' : '' !!}><a href="{{ route('widget.donation') }}"><i class="fa fa-users"></i> <span>Донат</span></a></li>
        </ul>
    </section>
</aside>